services:
  api_1: &api
    image: andersonfernandes/rinha-de-backend-2024-q1-ruby
    hostname: api_1
    environment:
      - DATABASE_URL=postgresql://admin:hTae9VsSoy86uKZ@db:5432/crebitos
      - RACK_ENV=production
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api_2:
    <<: *api
    hostname: api_2
    ports:
      - "5002:5000"

  load_balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_1
      - api_2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hTae9VsSoy86uKZ
      - POSTGRES_DB=crebitos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crebitos -h 0.0.0.0 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha_network
